In [7]:
import numpy as np

In [4]:
from time import process_time
python_list = [i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0


In [8]:
import numpy as np
from time import process_time
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0


In [9]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
#creating a 1 dimension
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a.shape

(4,)

In [10]:
#its a 2 dimensional
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape

(2, 4)

In [12]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
y=np.ones((3,3))
print(y)
#all ones in 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
z=np.full((5,4),3)
print(z)
#6 will the value which will fill the 5X4 matrix

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [16]:
#its an identity matrix
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
b=np.random.random((3,4))
print(b)

[[0.96670199 0.68286352 0.10192891 0.52920043]
 [0.39202761 0.67850487 0.87356684 0.16970308]
 [0.20576635 0.04317607 0.92654341 0.64236459]]


In [5]:
#LIST TO ARRAY USING NUMPY
import numpy as np
list2=[10,20,20,20,50]
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

In [7]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)


[[0 6 0]
 [4 1 6]
 [3 2 5]]
[[17 13 10]
 [15 12 15]
 [12 10 10]]


In [8]:
#Addition,Subtraction,Multiplication,Division
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))


[[17 19 10]
 [19 13 21]
 [15 12 15]]
[[-17  -7 -10]
 [-11 -11  -9]
 [ -9  -8  -5]]
[[ 0 78  0]
 [60 12 90]
 [36 20 50]]
[[0.         0.46153846 0.        ]
 [0.26666667 0.08333333 0.4       ]
 [0.25       0.2        0.5       ]]


In [14]:
#Transpose matrix
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[7 6]
 [0 3]
 [1 0]]
(3, 2)


In [11]:
a= np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[3 4 5]
 [0 9 5]]
(2, 3)


In [12]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[3 4]
 [5 0]
 [9 5]]
(3, 2)
